package:
  name: foo

  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}


source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - foo
  requires:
    - pytest
    - pytest-spec
    - pytest-cov
  commands:
    py.test --cov=foo tests/